# Generated by Django 5.1.4 on 2025-02-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0010_alter_logrow_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrow',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHomeApp.device'),
        ),
    ]
